name: Nix development cache
concurrency:
  group: nix-dev-cache-${{ github.ref_name }}
  cancel-in-progress: true
'on':
  push:
    branches:
    - trunk
    tags:
    - release/**
  workflow_dispatch: null
jobs:
  nix:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-24.04
        - ubuntu-latest
        - macos-15-intel
        - macos-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: mount Nix store on larger partition
      if: runner.os == 'Linux'
      run: 'sudo mkdir /nix /mnt/nix

        sudo mount --bind /mnt/nix /nix

        '
    - uses: cachix/install-nix-action@9280e7aca88deada44c930f1e2c78e21c3ae3edd
      if: runner.os == 'Linux'
      with:
        extra_nix_config: 'extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

          extra-substituters = https://cache.iog.io

          '
    - uses: cachix/install-nix-action@9280e7aca88deada44c930f1e2c78e21c3ae3edd
      if: runner.os != 'Linux'
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc
      with:
        name: unison
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: build all packages and development shells
      run: nix -L build --accept-flake-config --no-link --keep-going '.#all'
    - name: print disk free status
      if: always()
      run: df -h
